
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lacle_dev
    username: lacle
    password: lacle
  flyway:
    url: jdbc:postgresql://localhost:5432/lacle_dev
    user: lacle
    password: lacle
    baseline-on-migrate: true
#logging:
#  level:
#    root: debug